const FOOD_DATA = [
  {
    "name":"SE9",
    "brand":"Chemistry",
    "image":"icons8-chemistry-98.png"
  },{
    "name":"TE9",
    "brand":"Maths",
    "image":"icons8-maths-96.png"
  },
  {
    "name":"FE4",
    "brand":"Physics",
    "image":"icons8-physics-96.png"
  },
  {
    "name":"SE2",
    "brand":"History",
    "image":"fries.png"
  },
  {
    "name":"TE1",
    "brand":"Maths",
    "image":"ice_cream.png"
  },
  {
    "name":"Naaaaa",
    "brand":"aaaaa",
    "image":"noodles.png"
  },
  {
    "name":"aaaaaa",
    "brand":"aaaa",
    "image":"pizza.png"
  },
  {
    "name":"aaaaaaaaa",
    "brand":"aaa",
    "image":"sandwich.png"
  },
  {
    "name":"aaaaa",
    "brand":"nnnnnn",
    "image":"wrap.png"
  }
];